### ISSUE TITLE
Helm chart won't start due to "Error: unknown flag: --template-dir"

### ISSUE THREAD

**Issue by jwaibel-pons** [fjogeleit/policy-reporter#440]
I just tried to install policy-reporter via Helm chart, version 2.23.1, and all I get is

```
Error: unknown flag: --template-dir
Usage:
  policyreporter run [flags]
Flags:
      --burst int           K8s RESTClient burst (default 50)
  -c, --config string       target configuration file
  -d, --dbfile string       path to the SQLite DB File (default "sqlite-database.db")
  -h, --help                help for run
  -k, --kubeconfig string   absolute path to the kubeconfig file
      --lease-name string   name of the LeaseLock (default "policy-reporter")
  -m, --metrics-enabled     Enable Policy Reporter's Metrics API
      --pod-name string     name of the pod, used for leaderelection (default "policy-reporter")
  -p, --port int            http port for the optional rest api (default 8080)
      --profile             Enable application profiling with pprof
      --qps float32         K8s RESTClient QPS (default 20)
  -r, --rest-enabled        Enable Policy Reporter's REST API
      --worker int          amount of queue worker (default 5)
unknown flag: --template-dir

```

I just used the default values.yaml with no changes. The chart installed ghcr.io/kyverno/policy-reporter:2.18.1

**Comment by fjogeleit** [comment]
Hey, are you sure you run 2.23.1 and not 2.23.0? This issue was fixed with 2.23.1. The Policy Reporter version should be 2.19.0 by default.

**Comment by jwaibel-pons** [comment]
Yes, you are correct, my bad. Somehow an old values.yaml slipped into my installation. After doing a proper installation everything is working fine, Thanks for the swift response.

**Comment by jpmaas** [comment]
I just updated our installation to helm chart version 2.24.1 and app version 2.20.1 and the error still exists/happens again. The issue is not in the values file but in the templates/deployment.yaml file of the chart.
