### ISSUE TITLE
x509 certificate signed by unknown authority when using openIDConnect.enabled: true

### ISSUE THREAD

**Issue by larssb** [fjogeleit/policy-reporter#849]
I'm trying to enable OIDC support for the UI. We're running Keycloak internally and on a TLS certificate issued by a internal CA.

When doing this we get:

```text
k":"https://MY.DOMAIN/callback","discovery":"https://MY.DOMAIN/auth/realms/test-test/.well-known/openid-configuration"}                                                                     
 {"level":"error","ts":1743081340.444031,"caller":"config/resolver.go:273","msg":"failed to create openIDConnect provider","error":"Get \"https://MY.DOMAIN/auth/realms/test-test/.well-known/openid-configuration\": tls: failed to verify certificate: x509: certificate signed by unknown authority"}                   
 {"level":"error","ts":1743081340.4441736,"caller":"config/resolver.go:299","msg":"failed to setup oidc","error":"Get \"https://MY.DOMAIN/auth/realms/test-test/.well-known/openid-configuration\": tls: failed to verify certificate: x509: certificate signed by unknown authority"}                                     
 Error: Get "https://MY.DOMAIN/auth/realms/test-test/.well-known/openid-configuration": tls: failed to verify certificate: x509: certificate signed by unknown authority                                    
 Usage:                                                                                                          
   policy-reporter-ui run [flags]                                                                                
                                                                                                                 
 Flags:                                                                                                          
   -c, --config string                       target configuration file                                           
       --dev                                 Enable CORS Header for development                                  
   -h, --help                                help for run                                                        
       --kube-as string                      Username to impersonate for the operation                           
       --kube-as-group stringArray           Group to impersonate for the operation, this flag can be repeated to specify multiple groups.                                                                      
       --kube-as-uid string                  UID to impersonate for the operation                                
       --kube-certificate-authority string   Path to a cert file for the certificate authority                   
       --kube-client-certificate string      Path to a client certificate file for TLS                           
       --kube-client-key string              Path to a client key file for TLS                                   
       --kube-cluster string                 The name of the kubeconfig cluster to use                           
       --kube-context string                 The name of the kubeconfig context to use                           
       --kube-disable-compression            If true, opt-out of response compression for all requests to the server                                                                                            
       --kube-insecure-skip-tls-verify       If true, the server's certificate will not be checked for validity. This will make your HTTPS connections insecure                                                 
   -n, --kube-namespace string               If present, the namespace scope for this CLI request                
       --kube-password string                Password for basic authentication to the API server                 
       --kube-proxy-url string               If provided, this URL will be used to connect via proxy             
       --kube-request-timeout string         The length of time to wait before giving up on a single server request. Non-zero values should contain a corresponding time unit (e.g. 1s, 2m, 3h). A value of zero means don't timeout requests. (default "0")                                                                   
       --kube-server string                  The address and port of the Kubernetes API server                   
       --kube-tls-server-name string         If provided, this name will be used to validate server certificate. If this is not provided, hostname used to contact the server is used.                          
       --kube-token string                   Bearer token for authentication to the API server                   
       --kube-user string                    The name of the kubeconfig user to use                              
       --kube-username string                Username for basic authentication to the API server                 
       --local                               use kube config to connect to cluster                               
       --no-ui                               Disable the embedded frontend                                       
       --overwrite-host                      Overwrite Proxy Host and set Forward Header                         
       --port int                            PolicyReporter UI port (default 8080)                               
                                                                                                                 
 Get "https://MY.DOMAIN/auth/realms/test-test/.well-known/openid-configuration": tls: failed to verify certificate: x509: certificate signed by unknown authority  
```

I read the docs and can't find any option to specify/use the volume mounted certificate that should make the Kyverno Policy Reporter OIDC code trust the internal CA issued certificate that our Keycloak uses.

For e.g. the ui secret there's an option to use a `certificate` key.

Is it me being blind or is it **NOT** possible to use a internal/self-signed cert. with the Kyverno Policy Reporter when integrating with OIDC authentication?

Thank you very much.

**Comment by fjogeleit** [comment]
I will take a look on how to support certificates for the OIDC provider.

**Comment by larssb** [comment]
Okay thank you very much. So it wasn't me being blind. It's not supported yet.

Have a great day and I'm looking forward to it. Much appreciated.

**Comment by fjogeleit** [comment]
Yeah currently not

**Comment by fjogeleit** [comment]
Created https://github.com/kyverno/policy-reporter-ui/pull/497 need to release a new Helm Chart to make the cert configurable over helm values when the PR is merged.

**Comment by fjogeleit** [comment]
I released Helm Chart v3.1.0 - it supports a `openIDConnect.certificate` config which expects a file path to a cert/pem file.

**Comment by larssb** [comment]
Nice! I'll try it out and get back to this issue ASAP.

**Comment by larssb** [comment]
Unfortunately it seems to not be working yet.

In my `Helm values.yaml file` I'm doing:

```yaml
....
....
....
....
ui:
  ....
  ....
  ....
  ....
  openIDConnect:
    enabled: true
    callbackUrl: https://MY.DOMAIN/callback
    certificate: /tmp/ca_sub_cert/ca.crt
    clientId: kpr-test
    clientSecret: MY-CLIENT-SECRET
    discoveryUrl: https://MY.DOMAIN/auth/realms/test-test
```

Still seeing: `tls: failed to verify certificate: x509: certificate signed by unknown authority"}`

Looking at the `policy-reporter-ui-config Secret` I see that the `certificate: ` key is populated with the `/tmp/ca_sub_cert/ca.crt` path.

Am I missing something? N.B. the ca.crt **IS** volume mounted into the `UI Pod`.

Thank you so much.

---

I did control that the UI container image is at: `ghcr.io/kyverno/policy-reporter-ui:2.3.2` the `Helm Chart verson` is: `helm.sh/chart=policy-reporter-3.1.0`.

I also tried disabling `OIDC` again to verify that the `ca.crt` file is volume mounted - as it's in use by `basic auth.` integration with `Kyverno Policy Reporter` installations on downstream clusters.

That works fine.

**Comment by larssb** [comment]
Perhaps perhaps perhaps have I found the issue. With the caveat that I'm no master of `go code`!

Here:

[resolver.go](https://github.com/kyverno/policy-reporter-ui/blob/303db8c8db77c4edf9d2fd2ae9c7c7e506b01525/backend/pkg/config/resolver.go#L264-L272)

We have:

```go
	zap.L().Debug("setup openIDConnect", zap.String("callback", oid.Callback()), zap.String("discovery", oid.Discovery()))
	provider, err := openidConnect.New(oid.ClientID, oid.ClientSecret, oid.Callback(), oid.Discovery(), oid.Scopes...)
	if err != nil {
		zap.L().Error("failed to create openIDConnect provider", zap.Error(err))
		return nil, err
	}


	provider.HTTPClient = api.NewHTTPClient()
	if oid.Certificate != "" {
```

Shouldn't we "load" the `oid.Certificate` data into the instantiated `provider object`. Or is it simply because the `certificate path value` is not read into the `oid object`?

**Comment by fjogeleit** [comment]
The issue is that the call causing is already done in the constructor, before I have a chance to update the HTTPClient with the certificate.

I did a fork of the lib and added the client to the constructor function. Build an image you can test right now.

**Comment by larssb** [comment]
Aaah so a race condition .... kinda of the bootstrap ..... another path I was down. But, didn't feel convinced about it being that. I'll try to build an image a little later this evening. Have to go now. Thank you very much so far.

So I should build an image of the policy-reporter-ui project? Can't see any changes there.

**Comment by larssb** [comment]
aaah now I see it ...

**Comment by fjogeleit** [comment]
Can you try `ui.image.tag` = `2.3.3`?

The change is this commit: https://github.com/kyverno/policy-reporter-ui/commit/c8e145604ce543ec04af3abedae1f45816cf42de

**Comment by larssb** [comment]
Yes!!!!!!!! Now the ui pods came up. Testing further.

I don't know. Do we think this one is ready to close. I guess so.

**Comment by fjogeleit** [comment]
Yep, feel free to reopen it if you encounter any other issue,

**Comment by fjogeleit** [comment]
And just in case, we encountered issues with openIDConnect in an HA setup (more then 1 UI Pod) as the session files are not shared between pods. So you might need to run it with only 1 Pod for now.

**Comment by larssb** [comment]
Hehe yes I figured that out the hard way. The UI will throw:

```text
│ 2025-03-28T21:02:30.811362190Z policy-reporter-ui-785454858b-mrg57 {"level":"error","ts":1743195750.8111503,"ca │
│ ller":"auth/middleware.go:47","msg":"profile not found"}                                                        │
│ 2025-03-28T21:02:30.811579642Z policy-reporter-ui-785454858b-mrg57 {"level":"info","ts":1743195750.81142,"calle │
│ r":"zap@v1.1.4/zap.go:117","msg":"/","status":303,"method":"GET","path":"/","query":"","ip":"10.1.125.113","use │
│ r-agent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:136.0) Gecko/20100101 Firefox/136.0","latency":0.000241664 │
│ ,"time":"2025-03-28T21:02:30Z"}                                                                                 │
│ 2025-03-28T21:03:04.342758433Z policy-reporter-ui-785454858b-mrg57 {"level":"error","ts":1743195784.3425415,"ca │
│ ller":"auth/handler.go:24","msg":"failed to complete user","error":"could not find a matching session for this  │
│ request"} 
```

Is there an issue for this or a task somewhere I can track. I would like to run with multiple Pods at some point.

**Comment by fjogeleit** [comment]
I created https://github.com/kyverno/policy-reporter-ui/issues/501
